const FETCH_RENTALS = "FETCH_RENTALS";
const FETCH_RENTALS_SUCCESS = "FETCH_RENTALS_SUCCESS";
const FETCH_RENTALS_ERROR = "FETCH_RENTALS_ERROR";
const FETCH_RENTAL_BY_ID_SUCCESS = "FETCH_RENTAL_BY_ID";
const FETCH_RENTAL_BY_ID_INIT = "FETCH_RENTAL_BY_ID_INIT";
const FETCH_RENTALS_INIT = "FETCH_RENTALS_INIT";
const FETCH_RENTALS_FAIL = "FETCH_RENTALS_FAIL";

const FETCH_USER_BOOKINGS_SUCCESS = "FETCH_USER_BOOKINGS_SUCCESS";
const FETCH_USER_BOOKINGS_FAIL = "FETCH_USER_BOOKINGS_FAIL";
const FETCH_USER_BOOKINGS_INIT = "FETCH_USER_BOOKINGS_INIT";

const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";
const LOGOUT = "LOGOUT";

export default {
  FETCH_USER_BOOKINGS_SUCCESS,
  FETCH_USER_BOOKINGS_FAIL,
  FETCH_USER_BOOKINGS_INIT,
  FETCH_RENTALS,
  FETCH_RENTALS_SUCCESS,
  FETCH_RENTALS_ERROR,
  FETCH_RENTAL_BY_ID_SUCCESS,
  FETCH_RENTALS_INIT,
  FETCH_RENTALS_FAIL,
  FETCH_RENTAL_BY_ID_INIT,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT
};
