const FETCH_RENTALS = "FETCH_RENTALS";
const FETCH_RENTAL_BY_ID_SUCCESS = "FETCH_RENTAL_BY_ID";
const FETCH_RENTAL_BY_ID_INIT = "FETCH_RENTAL_BY_ID_INIT";

export default {
  FETCH_RENTALS,
  FETCH_RENTAL_BY_ID_SUCCESS,
  FETCH_RENTAL_BY_ID_INIT
};
